### ISSUE TITLE
Propose some place for discussion and help

### ISSUE THREAD

**Issue by silencej** [flatcar-linux/docs#120]
Usually the open source project will propose some places for help and discussion such as stackexchange (with a tag), slack group or discord group, etc, and recommend them in the documentation.

However I can't find any in flatcar documentation, and I also can't find any tags in stackexchange. I am not sure Github issues is a good place or not, thus I ask this question here for some clue.

Also an FAQ is very good for beginners.

**Comment by pothos** [comment]
Thanks for the suggestions, yes, would be good to have such information and FAQ in the docs (maybe even from reviewing the frequently asked questions on IRC and GitHub issues).

There is a short paragraph on the [website](https://www.flatcar-linux.org/) (search for `Getting help`), with links to the mailing lists (Google Groups) and the IRC channel.

**Comment by silencej** [comment]
I find the google groups is a good place. Thanks!
