### ISSUE TITLE
Name of the repository is confusing

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [flatcar-linux/docs#39]
The name of a `docs` repository under the `kinvolk` organization is not that clear as it contains only Flatcar Container Linux docs. A better name could be `https://github.com/kinvolk/flatcar-linux-docs`.

It is something like a fork of https://github.com/coreos/docs, it contains docs for all CoreOS related products, so in that case the name works fine but not in the kinvolk case.

**Comment by dongsupark** [comment]
Since the repo was renamed to `github.com/flatcar-linux/docs`, this issue is now done, I suppose.
